### ISSUE TITLE
Scrape complete list of votes

### ISSUE THREAD

**Issue by henare** [openaustralia/ukraine_verkhovna_rada_votes#2]
Once we've got a single vote event scraped (#1) we need to scrape All The Votes.

I'm not sure where this list is yet.

**Comment by henare** [comment]
From what I can tell so far we'll have to scrape this page, which contains all the bills:

http://w1.c1.rada.gov.ua/pls/zweb2/webproc2_5_1_J?ses=10009&num_s=2&num=&date1=&date2=&name_zp=&out_type=&id=&page=1

From there you visit each bill page, e.g. http://w1.c1.rada.gov.ua/pls/zweb2/webproc4_1?pf3511=55399

On that page the last tab contains a list of votes taken. The above example has two votes:
- http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_golos?g_id=2735
- http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_golos?g_id=2736

You can see the above URLs have sequential IDs. Could we just walk up the ID? Is there another page that has a list of every vote?

**Comment by mmitre** [comment]
There might be an alternate way, but @lisoffsky might want to confirm:
- Go to http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_pd2?day_=02&month_=09&year=2015&nom_s=3
- Look at the rows where the last column (Результат розгляду *) is not empty
- Follow the link. It should take you to a page like http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_sh?id_fakt=1591&nom_s=3
- In this page, you will see links to pages with voting results. These links seem to be followed by a short summary of the vote. For example, in the page above you have two links (both beginning with the words "Поіменне голосування" (roll-call):

11:16:38 - Поіменне голосування
Поіменне голосування про розгляд за скороченою процедурою проекту Закону про ратифікацію Договору між Україною та Республікою Сенегал про видачу правопорушників (№0045)
За-159 Проти-30 Утрималось-51 Не голосувало-91 Рішення прийняте
11:17:12-11:18:01 Петухов Сергій Ігорович
11:18:08-11:18:34 Гопко Ганна Миколаївна
11:18:42-11:20:28 Томенко Микола Володимирович
11:21:38 - Поіменне голосування
Поіменне голосування про проект Закону про ратифікацію Договору між Україною та Республікою Сенегал про видачу правопорушників (№0045) - в цілому
За-256 Проти-0 Утрималось-1 Не голосувало-74 Рішення прийняте

Yuri?

**Comment by lisoffsky** [comment]
Sorry for late response.
I think @henare has a better approach but I can't get how ids of each separate vote are connected to the draft law. 
Also, @henare please take into consideration that http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_golos?g_id=2735 voting is not a voting for a bill. That's a voting to vote that bill in a shorter procedure, so you can see that it passed in 197 votes (150 minimum for such type of voting).

**Comment by henare** [comment]
@mmitre & @lisoffsky thanks for the useful pointers :sparkles: 

> I think @henare has a better approach but I can't get how ids of each separate vote are connected to the draft law. 

I think I've mapped out a completely different approach to the ones we've looked at above. I'll put that in a separate comment.

> Also, @henare please take into consideration that http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_golos?g_id=2735 voting is not a voting for a bill.

I assume we want all votes, including ones like these? We definitely do that in the UK and Australia.

That vote is related to [bill 2980](http://w1.c1.rada.gov.ua/pls/zweb2/webproc4_2?id=&pf3516=2980&skl=9) and I think we should show it as such.

> That's a voting to vote that bill in a shorter procedure, so you can see that it passed in 197 votes (150 minimum for such type of voting).

This scraper already collects the result from the Rada directly (it's the `result` field of the `vote_event`). However the TVFY codebase doesn't use this at the moment so I've opened this issue so we know to change that: https://github.com/OPORA/publicwhip/issues/9

**Comment by henare** [comment]
OK, here's how I think we should approach scraping the complete list of votes. It follows a chronological approach by getting the list of days where there was a plenary session, then checks for any votes during that session, then gets the details of those votes.

The advantage of this is that it more closely models how the votes unfold and by extracting the list of votes from a day's agenda we can also link it back to its related bill (as this information is listed in the day's proceedings).

---

Visit the calendar page: http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_el_h

That page uses AJAX to show the sitting timetable per session. This page shows the sitting calendar for the 3rd session (`nom_s` is the session number):

http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_el_l?nom_s=3&ss=3

In that page you can discover links (hidden in CSS by default) to detail pages for each day that there's been a plenary session so far.

Here's an example of a day with no votes (the date is the `data` parameter): http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_el_h2?data=01092015&nom_s=3

And here's a day that had some votes: http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_el_h2?data=02092015&nom_s=3

From there we can extract vote details and link the back to their corresponding bills. Because these are date based, our scraper can be set to fetch recent days to get the data as it's posted.

**Comment by henare** [comment]
All done in 4f04eec...e63f86c

It fetches votes by date. To allow it to collect everything we can manually set a start date and then subsequent runs will start from the date of the most recent vote that has been scraped.
