### ISSUE TITLE
Add `debate_url`

### ISSUE THREAD

**Issue by henare** [openaustralia/ukraine_verkhovna_rada_votes#4]
Not sure what we should set this to. Is there a direct link to a speech related to a vote available?

**Comment by henare** [comment]
As far as I can tell there's no way to link to an individual speech that relates to a vote event.

I think we should set this to the day's proceedings, e.g. http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_el_h2?data=01092015&nom_s=3

**Comment by mmitre** [comment]
There might be a way to link a speech to a bill, but you're right, it seems
hard to link to a vote.

In terms of linking to a bill, @lisoffsky https://github.com/lisoffsky,
are all speeches under bill _3058_ at
http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_el_h2?data=17092015&nom_s=3
related to the bill?

**Comment by lisoffsky** [comment]
@mmitre you are right!

**Comment by henare** [comment]
Thanks @mmitre @lisoffsky, I'm going to go ahead with:

> I think we should set this to the day's proceedings, e.g. http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_el_h2?data=01092015&nom_s=3
