### ISSUE TITLE
Add `motion`

### ISSUE THREAD

**Issue by henare** [openaustralia/ukraine_verkhovna_rada_votes#5]

**Comment by henare** [comment]
For the [one vote](http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_golos?g_id=3106) we're getting so far we've set our own `title` field to the title shown on that page:

```
Поіменне голосування про включення до порядку денного сесії законопроектів №№ 2315а,2315а-1, 2156а, 2175а,2175а-1, 2311а, 2144а,2151а,2151а-1, 2244а,2244а-1,2244а-2, 2289а, 2309а, 2290а, 2174а, 2300а, 2310а, 2176а, 2216а, 2235а, 2230а, 2169а, 2234а, 2152а, 2222а, 2330а, 2263а, 2138а, 2158а, 2950, 2131а, 2547, 2168а, 2047а, 2048а, 2123а, 2101а, 2280а, 2281а, 2988, 2662-1, 2312а, 2308а, 2134а, 2960, 2092а, 2321а,2544,2855,2086а,2143а,2143а-1,2162а,2162а-1,2162а-2, 2317а, 2022а,2503, 2142а,2142а-1
```

That shows up in TVFY like this:

![selection_001](https://cloud.githubusercontent.com/assets/48945/10035068/9091d568-61d9-11e5-9161-bb637d8f315b.png)

According to [the document](https://docs.google.com/document/d/1oe_cEqBBvMFp2IbuUVcRxPSkVN78h0jTNjvcoCCwMKQ/edit#heading=h.dccf0jhql168) that's correct :+1: 

We also have a field in TVFY called `motion`. In the UK this is set to what the person says that is moving the motion, e.g. "_I move that the bill be read a third time_". In Australia we used to be able to do that but the parliamentary data no longer includes it.

In Australia we set the `motion` field to be the whole debate leading up to the vote. We don't display this but we do use it in search. This means you can find divisions where MPs are talking about something you're interested in.

It's also effectively the field we let you replace when you summarise a division on TVFY, i.e. what replaces the light yellow box in the screenshot above that starts, "_This division is yet to be summarised._"

@lisoffsky what should we set the `motion` field to, if anything, in our Ukrainian scraper?

**Comment by lisoffsky** [comment]
@henare, I think it would be good to have there a whole debate leading up to the vote. For now Rada isn't sharing transcripts in a convenient for splitting way.

**Comment by henare** [comment]
@lisoffsky thanks. It's not going to be easy but I think it can be done.

**Comment by henare** [comment]
It appears that there is a part of the day's transcript for each vote and it looks like it includes useful text.

[For example](http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_el_h2?data=14072015&nom_s=3), these three votes each have a corresponding timestamp in the transcript:

![selection_001](https://cloud.githubusercontent.com/assets/48945/10260491/a9216b6a-69b9-11e5-928e-2b50b612a4f5.png)
